stages:
  # - stage: validate
  #   jobs:
  #     - job: validate
  #       continueOnError: false
  #       steps:
  #         - task: TerraformInstaller@0
  #           inputs:
  #             terraformVersion: '0.14.9'
  #         - task: TerraformTaskV2@2
  #           displayName: init
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'init'
  #             backendServiceArm: 'terraform-scn'
  #             backendAzureRmResourceGroupName: 'terraform-rg'
  #             backendAzureRmStorageAccountName: 'harsha1985storageaccount'
  #             backendAzureRmContainerName: 'devopscontainer'
  #             backendAzureRmKey: 'terraform.tfstate'
  #             backendAWSBucketName: 
  #         - task: TerraformTaskV2@2
  #           displayName: validate
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'validate'

  - stage: deploy
    jobs:
      - deployment: deploy_terraform
        continueOnError: false
        environment: 'dev'
        strategy: 
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@0
                  displayName: 'install'
                  inputs:
                    terraformVersion: '0.14.9'

                - task: TerraformTaskV2@2
                  displayName: init
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    backendServiceArm: 'terraform-scn'
                    backendAzureRmResourceGroupName: 'terraform-rg'
                    backendAzureRmStorageAccountName: 'harsha1985storageaccount'
                    backendAzureRmContainerName: 'devopscontainer'
                    backendAzureRmKey: 'terraform.tfstate'
                    
                - task: TerraformTaskV2@2
                  displayName: 'plan'
                  inputs:
                    provider: 'azurerm'
                    command: 'plan'
                    environmentServiceNameAzureRM: 'terraform-scn'
                - task: TerraformTaskV2@2
                  displayName: 'deploy'
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    environmentServiceNameAzureRM: 'terraform-scn'